### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [annafelicia/prj-rev-bwfs-dasmoto#6]
Grade: Meets Expectations

Summary:
Anna, excellent job on the Dasmoto project! You did an excellent job using descriptive names for your ids, including the alt attribute, and correctly structuring your HTML files. You did have a small syntax issue(#1) and some style hiccups, but those should be relatively simple for you to fix.

As you work on future projects, consider commenting both your HTML and CSS files. Usually down the road, we all end up working in teams and for our fellow teammates to understand our code, commenting all our files is essential. Apart from promoting collaboration, it helps one know what our code is doing once our projects get complex. 

As extra practice consider using [linear gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient). Using gradients make it simple to add a unique look to any element on a page.

**Comment by annafelicia** [comment]
Hi Jim!

Thank you for your feedback - all very valuable and a great support in accelerating my learning experience! 

I'll make the changes you suggested and will make sure to remember them in the future.

Again, big thank you!
